### ISSUE TITLE
ws server trigger panic down in iovec

### ISSUE THREAD

**Issue by faern** [paritytech/jsonrpc#207]
I get the following stacktrace on Windows:

```
thread '<unnamed>' panicked at 'this crate accidentally accepted 0-sized slices originally but this was since discovered as a soundness hole, it's recommended to use the `from_bytes` function instead', src\libcore\option.rs:819:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_new
   4: std::panicking::begin_panic_fmt
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::option::expect_failed
   8: <core::option::Option<T>>::expect
             at C:\projects\rust\src\libcore/option.rs:302
   9: <&'a iovec::IoVec as core::convert::From<&'a [u8]>>::from
             at C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\iovec-0.1.1\src/lib.rs:109
  10: <T as core::convert::Into<U>>::into
             at C:\projects\rust\src\libcore/convert.rs:398
  11: mio::sys::windows::tcp::TcpStream::write
             at C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.6.10\src\sys\windows/tcp.rs:329
  12: <mio::net::tcp::TcpStream as std::io::Write>::write
             at C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.6.10\src\net/tcp.rs:398
  13: <ws::stream::Stream as std::io::Write>::write
             at C:\Users\appveyor\.cargo\git\checkouts\ws-rs-d6df248983fbaaf0\f8306a7\src/stream.rs:190
  14: ws::stream::TryWriteBuf::try_write_buf
             at C:\Users\appveyor\.cargo\git\checkouts\ws-rs-d6df248983fbaaf0\f8306a7\src/stream.rs:51
  15: <ws::connection::Connection<H>>::write
             at C:\Users\appveyor\.cargo\git\checkouts\ws-rs-d6df248983fbaaf0\f8306a7\src/connection.rs:823
  16: <ws::io::Handler<F>>::handle_event
             at C:\Users\appveyor\.cargo\git\checkouts\ws-rs-d6df248983fbaaf0\f8306a7\src/io.rs:572
  17: <ws::io::Handler<F>>::event_loop
             at C:\Users\appveyor\.cargo\git\checkouts\ws-rs-d6df248983fbaaf0\f8306a7\src/io.rs:419
  18: <ws::io::Handler<F>>::run
             at C:\Users\appveyor\.cargo\git\checkouts\ws-rs-d6df248983fbaaf0\f8306a7\src/io.rs:386
  19: <ws::WebSocket<F>>::run
             at C:\Users\appveyor\.cargo\git\checkouts\ws-rs-d6df248983fbaaf0\f8306a7\src/lib.rs:330
  20: jsonrpc_ws_server::server::Server::start::{{closure}}
             at C:\Users\appveyor\.cargo\git\checkouts\jsonrpc-22a65938f7d26b63\21de52a\ws\src/server.rs:82
```

`iovec 0.1.1` added that panic to cover a soundness hole. The problem is that now I get this panic. I have not yet figured out if the invalid usage of `iovec` stem from `jsonrpc-ws-server`, `ws` or `mio`. But I suspect one of the first two, which are both relevant in this repo, since we use a fork of `ws`.

I did try to run the same code with a version of `jsonrpc-ws-server` using the latest upstream `ws` commit, but that failed with the same error, so if the bug is in `ws` it's not fixed yet.

**Comment by faern** [comment]
Looks like this was fixed by `mio 0.6.11`.
